### ISSUE TITLE
Untag command leaves behind a duplicate of the old interval with the tag

### ISSUE THREAD

**Issue by mmeier86** [GothenburgBitFactory/timewarrior#302] opened 2020-04-09 15:44 UTC
Hello Timewarrior team,

while trying to do some tag renaming, I encountered a problem where `timew untag @4711 foobar` would create a duplicate of the 4711 interval. I'd end up with two copies of `@4711`, one with `foobar` still in the tags and one without.

### Versions Info

I was able to reproduce this behavior on the same interval in my database with both the current v1.2.0 release version (my original version) and with the most current commit on the `dev` branch, 0e5e3316caa812400dda13d5b7cbe7a0e9eebcc5. For both versions, I worked with a build directly from the repository.

```
timew 1.2.0
       Platform: Linux

Compiler:
        Version: Clang 9.0.1 
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Apr  9 2020 17:02:55
         Commit: 0e5e331
          CMake: 3.16.5
     Build type: Release

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/michael/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
       Database: /home/michael/.timewarrior (drwx 4096 bytes)
        $EDITOR: /usr/bin/emacsclient -c
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/michael/.timewarrior/extensions (drwx 4096 bytes)
                 /home/michael/.timewarrior/extensions/totals.py (-rwx 4340 bytes)

```

### Reproduction

Now, producing a working reproduction with the newest Timewarrior Dev commit proved tricky. Please see the following section.

### Possible Root Cause

After looking through the code, I believe I've found the problem in https://github.com/GothenburgBitFactory/timewarrior/blob/0e5e3316caa812400dda13d5b7cbe7a0e9eebcc5/src/Datafile.cpp#L135

If I print the value of `serialized`, and also print out the content of `_lines`, I get the following (anonymized) results:

```
Content of the serialized variable:
inc 20180412T214608Z - 20180412T224800Z # "Anonymized text" tag1 "c_lang" tag2 tag3
The relevant line as printed from _lines:
inc 20180412T214608Z - 20180412T224800Z # "Anonymized text" tag1 c_lang tag2 tag3
```

I haven't anonymized `c_lang`, that's the actual tag I'm seeing in my database. Please note that the date of the interval fits the time around which it was created,  with a Timewarrior version < 1.2.0.

Note that in the modified version, as the interval to be removed, the `c_lang` tag is quoted, but in my datafile, it isn't. Which is why I've left the tag as it is. 

Is it possible that you started quoting all tags at some point in newer Timewarrior versions?

Anyway, this is the reason I'm getting duplicates of my interval when trying to remove a tag. The deletion fails (silently, it seems?) but the addition of the new interval without the removed tag still goes through, and I end up with a duplicate interval.

I can also confirm that this is not a general problem. The renaming of other tags via tag/untag works fine, but as soon as a `_` shows up, I get duplicates.

**Comment by sruffell** [comment] 2020-04-09 16:12
This is a good bug report. I was able to reproduce quickly.

I'm not sure why it was changed since there isn't an issue around the commit, but this is when tags with underscores started to be quoted in the datafile: 7e6c09c6e3c4ce818c30e9e025157481f2ea141f

But yes, there do appear to be two bugs like you said. modifyInterval should definitely fail if it cannot "find" the interval in the datafile.

For users with databases with old files, I believe this could be allowed to work with the various quoting styles by not trying to match by line in the database, but instead by "Interval" object, which will get rid of any quotes if needed.

**Comment by sruffell** [comment] 2020-04-09 16:24
Actually, I did check and the https://github.com/GothenburgBitFactory/timewarrior/files/3600911/timew-dbcorrection-current-version.zip script will update an older database to the new format, quoting any tags that are necessary.

Although a quick search didn't show me where it's documented that you need to run the script when updating to 1.2.0. I just remember @lauft mentioning it on another issue.

But I still believe it's a bug that modify interval silently fails on the delete step.

**Comment by mmeier86** [comment] 2020-04-09 19:00
Thanks a lot for the quick reply. And sorry for the bogus bug report. I completely missed that script. I'm letting it run now, seems to take a while on 28000 intervals. 

I'll report back to confirm that it worked once it has run through. Should I then close the ticket, or should I keep it open for the check if the deletion was successful before adding the modified interval in `modifyInterval`?

**Comment by sruffell** [comment] 2020-04-09 20:32
I personally think this should stay open since timewarrior shouldn't corrupt the database if the script wasn't run.

Also, with 28000 intervals, you probably want to use the current dev branch instead of 1.2.0, since there is work there to avoid loading the entire database when you only want to deal with recent intervals (#245) that is slotted for 1.3.0.

**Comment by mmeier86** [comment] 2020-04-10 16:46
I can now confirm that after running the database cleanup script, I'm not getting any duplicate intervals any more. And thanks for the tip to go to the current Dev branch. The script, as well as dayly use, are now way faster.

**Comment by lauft** [comment] 2020-05-06 07:39
No more actions seem to be necessary here, so I am closing this.

**Closed by lauft** 2020-05-06 07:39 UTC
Labels: bug, fixed

**Comment by sruffell** [comment] 2020-05-06 13:55
@lauft I think this may need to stay open (or we want to open a new issue).

The existing problem that I see is that Database::modifyInterval will add an interval even if there is a failure when deleting the interval.

**Comment by lauft** [comment] 2020-05-06 14:47
> The existing problem that I see is that Database::modifyInterval will add an interval even if there is a failure when deleting the interval.

@sruffell In that case please open a separate issue (with a small reproducing script) so we can track this separately
