### ISSUE TITLE
Please support 'timew break'

### ISSUE THREAD

**Issue by bzed** [GothenburgBitFactory/timewarrior#281] opened 2020-01-30 17:32 UTC
Hi,

Austrian law requires you to do daily breaks and to track them. But they also do not count to the daily work time. Tracking this properly is not possible with timewarrior as stop + start is not necessarily accountable as a break during your work time. Could you implement a tracking for that? Maybe also with a way to enforce a minimum time for a break, or better, configurable rules, as every country has some other requirement for that?

Thanks a lot,
Bernd

**Comment by sruffell** [comment] 2020-02-01 10:58
I wonder if it would be more useful if the `timew summary` and `timew export` had a way to filter *out* intervals with a certain tag.  Then you could do something like: `timew summary -break :week` to see your "working time" for the current week and `timew summary break :week` to see only your break time for the week.

What do you think?

**Comment by lauft** [comment] 2020-02-01 16:12
What you already can do with the current version of Timewarrior:
* Track your breaks like your usual work intervals, but give each a distictive tag:
  ```
   $ timew start WORK TASK1
   $ timew start BREAK
   $ timew start WORK TASK2
   $ timew start BREAK
   ...
  ```
* Install the `totals` extension (located in the project directory `ext/`) and use it with a tag filter:
  ```
   $ timew totals WORK :week
   Total by Tag, for 2020-01-27 00:00:00 - 2020-02-03 00:00:00

   Tag        Total
   TASK1    1:00:13
   TASK2    1:00:08
   WORK     2:00:21
            -------
   Total    4:00:42
   ```

Not perfect (e.g. the real total is the number next to `WORK`, not the last line), but a start. 

> I wonder if it would be more useful if the timew summary and timew export had a way to filter out intervals with a certain tag.

@sruffell There is already #209 which would add the possiblity to filter out certain tags when calling commands like `summary` or `export`. But the filtering should not be a feature of the command(s) but encapsulated into a filter object passed to the database.

Another solution would be to implement a custom report which handles all the user specific requirements like tag filtering, minmal break length and beyond. 

> Maybe also with a way to enforce a minimum time for a break, or better, configurable rules,...

@bzed What exactly do you mean by "enforce"? Should Timewarrior not allow another call to command `start` before the current running break has reached a certain length?

**Comment by bzed** [comment] 2020-02-01 19:14
@sruffell yes, filtering tags would work, absolutely. Preferable this should work for all commands.

@lauft not necessarily blocking start, but - for example - by tracking the time for the newly started work after the minimum break. And regarding the totals extension - yes, I have my own extension doing magic stuff I need at work, but I'd like to see this in the commands shipped with timew so I don't have to reimplement them in Python.

**Comment by sruffell** [comment] 2020-02-01 21:31
@bzed, @lauft  I really need to go through some of the older issues. It sounds like this one can be closed since it could essentially be considered a duplicate of #209?

**Comment by bzed** [comment] 2020-02-02 14:14
@sruffell yes, indeed, it is.

**Comment by lauft** [comment] 2021-06-11 06:05
Duplicate of #209 -> closed.

**Closed by lauft** 2021-06-11 06:05 UTC
Labels: discussion, duplicate
