### ISSUE TITLE
[mac os x] [1.2.0] on an upgraded catalina installation getting "access error 2: No such file or directory"

### ISSUE THREAD

**Issue by arooni** [GothenburgBitFactory/timewarrior#264] opened 2019-11-21 23:09 UTC
REPRO:
Upgrade your version of mac os x from whatever was before catalina to catalina.  
Run timew
```
[I]  ~/.timewarrior  timew
access error 2: No such file or directory
```
Get that error.  

```
#import /home/david/.timewarrior/dark.theme
#import /home/david/.timewarrior/holidays.en-US

```

Investigate your config file.  Commenting out both of these lines makes it run again fine.  But what's weird is that both files exist in the right place; and I even changed permissions to 777 to see if that was it and it's not.  Seems like import doesn't want to work on this version of os

[I]  ~/.timewarrior  python --version
Python 2.7.17
[I]  ~/.timewarrior  python3 --version
Python 3.7.5

ideas?

**Comment by lauft** [comment] 2019-11-28 20:05
Weird... Some ideas that come to my mind:
* What is the output of `timew diagnostics`?
* Does the `:debug` hint reveal more information?
* Can you test whether the problem persists with Timewarrior 1.2.0?

**Comment by arooni** [comment] 2019-11-30 00:32
oopsies. apparently i had 1.2.0; 
```
[I]  ✘  ~  timew diagnostics

timew 1.2.0
       Platform: Darwin

Compiler:
        Version: 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.12)
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Nov 29 2019 16:17:45
          CMake: 3.15.5
     Build type: Release

Configuration
  TIMEWARRIORDB: -
            Cfg: /Users/david/.timewarrior/timewarrior.cfg (-rw- 748 bytes)
       Database: /Users/david/.timewarrior (drwx 416 bytes)
        $EDITOR: vim
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /Users/david/.timewarrior/extensions (drwx 128 bytes)
                 /Users/david/.timewarrior/extensions/toggl.py (-rw- 9123 bytes)
                 /Users/david/.timewarrior/extensions/totals.py (-rwx 3606 bytes)
```

Also when i added back in the line:
```
[I]  ✘  ~/.timewarrior  timew :debug
Could not read imported file '/home/david/.timewarrior/dark.theme'.
>> Timer timew 0.003729 sec
```

**Comment by lauft** [comment] 2019-12-22 12:59
I wonder whether this is Timewarrior only or also pops up on other occasions. Can you try a fresh install of Timewarrior?

Unfortunately I do not have macOS 10.15 at hand to investigate myself...

**Comment by sruffell** [comment] 2020-01-04 04:52
I use macOS 10.15 and have not run into this problem.

**Comment by Rom1deTroyes** [comment] 2020-05-10 16:31
Today I get this error on a Debian10 installation :
```sh
❯ timew
access error 2: No such file or directory
❯ which timew
/usr/bin/timew
❯ ls -lha /usr/bin/timew
-rwxr-xr-x 1 root root 799K mai    6  2018 /usr/bin/timew
❯ /usr/bin/timew
access error 2: No such file or directory
❯ /usr/bin/timew diagnostics
access error 2: No such file or directory
❯ /usr/bin/timew :debug
access error 2: No such file or directory
>> Timer timew 0.000803 sec
❯ /usr/bin/timew --version
1.1.1
❯ uname -a
Linux Mach 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
```

Installing from github repo on `~/.local` seems to resolve the problem.

```sh
❯ ~/.local/bin/timew
Tags database does not exist. Recreating from interval data...
Tracking TimeWarriorTuto
  Started 2020-05-09T14:22:13
  Current         10T18:27:13
  Total              28:05:00
❯ ~/.local/bin/timew --version
1.3.0
```

The `Tags database does not exist. Recreating from interval data...` could be a way to investigate ?

(thanx for this great tool, btw :-)

**Comment by sruffell** [comment] 2020-05-11 04:14
Was this a fresh install? Do you have special apparmor profiles enabled? Also, if you want to proceed with investigating, you probably want to create a new issue since you are talking about Debian and not Catalina.

That said, when I do a fresh install on Debian 10 I was unable to reproduce.  See below:

```
$ sudo apt install timewarrior
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  timewarrior
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 278 kB of archives.
After this operation, 876 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 timewarrior amd64 1.1.1+ds.1-1 [278 kB]
Fetched 278 kB in 0s (1,462 kB/s)
Selecting previously unselected package timewarrior.
(Reading database ... 41411 files and directories currently installed.)
Preparing to unpack .../timewarrior_1.1.1+ds.1-1_amd64.deb ...
Unpacking timewarrior (1.1.1+ds.1-1) ...
Setting up timewarrior (1.1.1+ds.1-1) ...
Processing triggers for man-db (2.8.5-2) ...
$ which timew
/usr/bin/timew
$ timew --version
1.1.1
$ uname -a
Linux contrib-buster 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
$ timew start test
Create new database in /home/vagrant/.timewarrior? (yes/no) yes
Tracking test
  Started 2020-05-11T02:13:10
  Current                  10
  Total               0:00:00
$ timew summary

Wk  Date       Day Tags   Start End    Time   Total
W20 2020-05-11 Mon test 2:13:10   - 0:00:03 0:00:03

                                            0:00:03


                                            0:00:02

```

**Comment by lauft** [comment] 2020-08-20 16:25
I am closing this due to the scarce information available. The problem does not seem to show up generally on every installation and a workaround (doing a manual install) does exist.

**Closed by lauft** 2020-08-20 16:25 UTC
Labels: bug, won't fix
