### ISSUE TITLE
Internal error. Failed encode / decode check. on modify

### ISSUE THREAD

**Issue by gms8994** [GothenburgBitFactory/timewarrior#422] opened 2021-05-11 16:23 UTC
Version: 1.4.2
OS: MACOS 10.15.7

This seems somewhat related to #416 

`timew start TRACKER-6145`
```
Tracking "TRACKER-6145"
  Started 2021-05-11T12:12:43
  Current                  43
  Total               0:00:00
```
`timew modify start @1 12:02`
```
Internal error. Failed encode / decode check.
```

`timew modify start @1 12:02 :debug`
```CLI Parser
  _original_args
    timew modify start @1 12:02 :debug
  _args
    word basename='timew' raw='timew' BINARY 
    word canonical='modify' raw='modify' ORIGINAL CMD 
    word raw='start' ORIGINAL FILTER TAG 
    word raw='@1' value='1' ORIGINAL ID FILTER 
    date raw='12:02' ORIGINAL FILTER 
    word canonical=':debug' raw=':debug' ORIGINAL HINT FILTER 

>> 2021-05.data: 14 intervals
>> Found 0 holidays
>> Found 7 exclusions
>> 2021-05.data: Deleted inc 20210511T161243Z # "TRACKER-6145"
>> 2021-05.data: Added inc 20210511T161243Z # "TRACKER-6145"
>> Found 0 holidays
>> Found 7 exclusions
>> 2021-05.data: Deleted inc 20210511T161243Z # "TRACKER-6145"
>> Loaded 0 tracked intervals
>> Datafile::addInterval() failed.
>> Encode / decode check failed:
>>   inc 20210511T160200Z # "TRACKER-6145"
>> is not equal to:
>>   inc 20210511T160200Z # "TRACKER-6145"
Internal error. Failed encode / decode check.
>> Timer timew 0.004484 sec
```

**Comment by sruffell** [comment] 2021-05-11 16:43
@gms8994 Are you able to try with the current dev branch? I believe the fix for this issue is the same as #416, because the TRACKER-6145 ends up getting quoted internally.

**Comment by sruffell** [comment] 2021-05-11 17:20
You would need to build it manually. @lauft will have to comment on when the next release is planned.

**Comment by gms8994** [comment] 2021-05-11 17:35
I'll give that a shot. Something I noticed, it doesn't seem to fail if the task is not currently active - ie, if I've done `timew stop` then I can do `timew modify` successfully. I don't know if that has any bearing, but I'll do my best to determine if the dev branch fixes the issue.

**Comment by lauft** [comment] 2021-05-11 20:10
@gms8994 Unfortunately I could not reproduce your error (see my reproducing script below), both version `1.4.2` and `dev` work fine on my machine (macOS 10.14).

The next release is not scheduled yet, but if you can confirm that the current `dev` version fixes the issue for you, I could create a `1.4.3` bugfix release. Please note that we do not maintain the packages, an update there is in the hands of the respective maintainers. However in my experience Homebrew was rather fast to respond...

My reproducing script (`TI-422.sh`), run from the local checkout of the repository:
```bash
#!/usr/bin/env bash

TODAY=$( date "+%Y%m%d" )
YESTERDAY=$( date -v -1d "+%Y%m%d" )
CURRENT_HOUR=$( date "+%k" )

function get_current_date_with_delta()
{
  local delta=${1}

  (( hour = CURRENT_HOUR + delta ))

  if [[ ${hour} -lt 0 ]] ; then
    (( hour = hour + 24 ))
    date=${YESTERDAY}
  else
    date=${TODAY}
  fi

  if [[ ${hour} -lt 10 ]] ; then
    hour="0${hour}"
  fi

  echo "${date}T${hour}0000"
}

# Create test environment in /tmp/timewarriordb
export TIMEWARRIORDB=/tmp/timewarriordb
rm -rf ${TIMEWARRIORDB}
mkdir -p ${TIMEWARRIORDB}/data
:> ${TIMEWARRIORDB}/timewarrior.cfg

one_hour_before=$(get_current_date_with_delta "-1") 

src/timew start TRACKER-6145
cat /tmp/timewarriordb/data/*.data
src/timew modify start @1 "${one_hour_before}"
cat /tmp/timewarriordb/data/*.data
```
Output:
```
$ ./TI-422.sh 
Note: '"TRACKER-6145"' is a new tag.
Tracking "TRACKER-6145"
  Started 2021-05-11T22:01:37
  Current                  37
  Total               0:00:00
inc 20210511T200137Z # "TRACKER-6145"
inc 20210511T190000Z # "TRACKER-6145"
```

**Comment by sruffell** [comment] 2021-05-12 15:32
Thinking about this some more, I was trying to answer why the debug output showed the before and after interval serializations the same:
```
>> Encode / decode check failed:
>>   inc 20210511T160200Z # "TRACKER-6145"
>> is not equal to:
>>   inc 20210511T160200Z # "TRACKER-6145"
```

Looking at the source code, the only way that should be possible is if one of the intervals is synthetic.

I modified @lauft's reproducer to add exclusions and I was able to reproduce on 1.4.2 and the current dev branch.

Script:
```bash
#!/usr/bin/env bash
set -e

TODAY=$( date "+%Y%m%d" )
YESTERDAY=$( date -v -1d "+%Y%m%d" )
CURRENT_HOUR=$( date "+%k" )

function get_current_date_with_delta()
{
  local delta=${1}

  (( hour = CURRENT_HOUR + delta ))

  if [[ ${hour} -lt 0 ]] ; then
    (( hour = hour + 24 ))
    date=${YESTERDAY}
  else
    date=${TODAY}
  fi

  if [[ ${hour} -lt 10 ]] ; then
    hour="0${hour}"
  fi

  echo "${date}T${hour}0000"
}

# Create test environment in /tmp/timewarriordb
export TIMEWARRIORDB=/tmp/timewarriordb
rm -rf ${TIMEWARRIORDB}
mkdir -p ${TIMEWARRIORDB}/data
:> ${TIMEWARRIORDB}/timewarrior.cfg

one_hour_before=$(get_current_date_with_delta "-1")

src/timew config journal.size 2 :yes
src/timew config exclusions.monday '>0:00' :yes
src/timew config exclusions.tuesday '>0:00' :yes
src/timew config exclusions.wednesday '>0:00' :yes
src/timew config exclusions.thursday '>0:00' :yes
src/timew config exclusions.friday '>0:00' :yes

src/timew start TRACKER-6145
src/timew modify start @1 "${one_hour_before}" :debug
for file in /tmp/timewarriordb/data/*.data ; do
        echo -e "\n=== $file ================ "
        cat $file
done
```

Output:

```bash
$ bash TI-422.sh
Config file /tmp/timewarriordb/timewarrior.cfg modified.
Config file /tmp/timewarriordb/timewarrior.cfg modified.
Config file /tmp/timewarriordb/timewarrior.cfg modified.
Config file /tmp/timewarriordb/timewarrior.cfg modified.
Config file /tmp/timewarriordb/timewarrior.cfg modified.
Config file /tmp/timewarriordb/timewarrior.cfg modified.
Note: '"TRACKER-6145"' is a new tag.
Tracking "TRACKER-6145"
  Started 2021-05-11T20:26:48
  Current                  48
  Total               0:00:00
CLI Parser
  _original_args
    src/timew modify start @1 20210511T190000 :debug
  _args
    word basename='timew' raw='src/timew' BINARY
    word canonical='modify' raw='modify' ORIGINAL CMD
    word raw='start' ORIGINAL FILTER TAG
    word raw='@1' value='1' ORIGINAL ID FILTER
    date raw='20210511T190000' ORIGINAL FILTER
    word canonical=':debug' raw=':debug' ORIGINAL HINT FILTER

>> 2021-05.data: 1 intervals
>> Found 0 holidays
>> Found 5 exclusions
>> 2021-05.data: Deleted inc 20210512T012648Z # "TRACKER-6145"
>> 2021-05.data: Added inc 20210512T012648Z # "TRACKER-6145"
>> Found 0 holidays
>> Found 5 exclusions
>> 2021-05.data: Deleted inc 20210512T012648Z # "TRACKER-6145"
>> Loaded 0 tracked intervals
>> Datafile::addInterval() failed.
>> Encode / decode check failed:
>>   inc 20210512T000000Z # "TRACKER-6145"
>> is not equal to:
>>   inc 20210512T000000Z # "TRACKER-6145"
Internal error. Failed encode / decode check.
>> Timer timew 0.007102 sec
```

I'll dig into it more this evening, but just wanted to let @gms8994 know that there is no need to try the dev branch currently (and thanks for reporting the issue).

**Comment by sruffell** [comment] 2021-05-12 15:35
@gms8994 also, if you could share the exclusions you have configured, I would appreciate it.

**Comment by gms8994** [comment] 2021-05-12 16:03
@sruffell I'm glad to know that I found an actual issue! My exclusions are as follows:

```
exclusions.monday = <8:30 11:30-13:15 >17:00
exclusions.tuesday = <8:30 11:30-13:15 >17:00
exclusions.wednesday = <8:30 11:30-13:15 >17:00
exclusions.thursday = <8:30 11:30-13:15 >17:00
exclusions.friday = <8:30 11:30-13:15 >17:00
exclusions.saturday = >0:00
exclusions.sunday = >0:00
```

Thank you for your persistence. I know how difficult troubleshooting can be, and I appreciate it!

**Closed** 2021-05-16 10:43 UTC
Labels: bug

**Comment by lauft** [comment] 2021-05-16 11:13
@gms8994 Now that @sruffell has supplied a fix for this issue I am compiling the `1.4.3` bugfix release.

**Comment by lauft** [comment] 2021-05-28 12:32
@gms8994 Release `1.4.3` is out. I hope the package maintainers catch up quickly... 🤞🏻

**Comment by gms8994** [comment] 2021-06-08 16:09
@lauft Homebrew has updated, and I've confirmed that 1.4.3 does fix the issue - thank you and team so much for your work!
