### ISSUE TITLE
Tag containing double quotes breaks TimeWarrior v1.2.0

### ISSUE THREAD

**Issue by sskras** [GothenburgBitFactory/timewarrior#220] opened 2019-04-15 16:54 UTC
And if I use double quotes from the Task Warrior, TimeW doesn't break.

I tested TimeWarrior in sandbox on MSys2, not on Linux:
```
$ timew --version
1.2.0

$ uname -a
MSYS_NT-10.0 SAUKRSXM1 2.11.1(0.329/5/3) 2018-09-10 14:19 x86_64 Msys

$ rm -r $TIMEWARRIORDB
$ rm -r $TASKDATA

$ export TASKDATA=/tmp/.task
$ export TIMEWARRIORDB=/tmp/.timew

$ mkdir -p $TASKDATA/hooks
$ mkdir $TIMEWARRIORDB

# Both showing empty lists:

$ task
TASKDATA override: /tmp/.task
[task next]
No matches.

$ timew summ
No filtered data found in the range 2019-04-15T00:00:00 - 2019-04-16T00:00:00.

# Link them together:

$ cp -v /usr/local/share/doc/timew/ext/on-modify.timewarrior /tmp/.task/hooks/
'/usr/local/share/doc/timew/ext/on-modify.timewarrior' -> '/tmp/.task/hooks/on-modify.timewarrior'
```

Initialize two tasks:

```
# Task #1 created:

$ task add proj:TEST 'first task'
TASKDATA override: /tmp/.task
Created task 1.
The project 'TEST' has changed.  Project 'TEST' is 0% complete (1 task remaining).

$ task
TASKDATA override: /tmp/.task
[task next]

ID Age Project Description Urg
 1 3s  TEST    first task     1

1 task

# ... and started:

$ task 'first task' start
Starting task 228da0ea-13e0-444e-922e-dcc326a175ea 'first task'.
Started 1 task.
TASKDATA override: /tmp/.task
Note: 'TEST' is a new tag.
Note: '"first task"' is a new tag.
Tracking TEST "first task"
  Started 2019-04-15T18:50:02
  Current                  02
  Total               0:00:00
Project 'TEST' is 0% complete (1 task remaining).

# ... it's being time-tracked too:

$ timew summ

Wk  Date       Day Tags                Start End    Time   Total
W16 2019-04-15 Mon TEST, first task 18:50:02   - 0:00:05 0:00:05

                                                         0:00:05

# Task #2 created (including double quotes):

$ task add proj:TEST 'second task containing \"double\" quotes'
TASKDATA override: /tmp/.task
Created task 2.
The project 'TEST' has changed.  Project 'TEST' is 0% complete (2 of 2 tasks remaining).

$ task
TASKDATA override: /tmp/.task
[task next]

ID Active Age  Project Description                            Urg
 1 40s    1min TEST    first task                                5
 2        16s  TEST    second task containing "double" quotes    1

2 tasks

# Task #1 stopped:

$ task 'first task' stop
Stopping task 228da0ea-13e0-444e-922e-dcc326a175ea 'first task'.
Stopped 1 task.
TASKDATA override: /tmp/.task
Recorded TEST "first task"
  Started 2019-04-15T18:50:02
  Ended                 51:19
  Total               0:01:17
Project 'TEST' is 0% complete (2 of 2 tasks remaining).

# Task #2 listed:

$ task '/second task/'
TASKDATA override: /tmp/.task
[task next ( /second task/ )]

ID Age  Project Description                            Urg
 2 1min TEST    second task containing "double" quotes    1

1 task

# ... and started:

$ task '/second task/' start
Starting task 6149e8f0-aa72-4280-b584-01d6ae475b00 'second task containing "double" quotes'.
Started 1 task.
TASKDATA override: /tmp/.task
Note: '"second task containing double quotes"' is a new tag.
Tracking TEST "second task containing double quotes"
  Started 2019-04-15T18:52:08
  Current                  08
  Total               0:00:00
Project 'TEST' is 0% complete (2 of 2 tasks remaining).

# Tasks list:

$ task
TASKDATA override: /tmp/.task
[task next]

ID Active Age  Project Description                            Urg
 2 10s    1min TEST    second task containing "double" quotes    5
 1        2min TEST    first task                                1

2 tasks
```

Task list has two tasks and contains double quotes.
Tracked time now includes task #2 too, but its double quotes are missing:

```
$ timew summ :id


Wk  Date       Day ID Tags                                          Start      End    Time   Total
W16 2019-04-15 Mon @2 TEST, first task                           18:50:02 18:51:19 0:01:17
                   @1 TEST, second task containing double quotes 18:52:08        - 0:00:39 0:01:56

                                                                                           0:01:56
```

Add tracked time for the third (non-existing) task manually (using the same string format as in TaskWarrior):

```
$ timew track 16:00 - 17:00 TEST 'tagging third task containing \"double\" quotes directly into TimeW'
Note: '"tagging third task containing \"double\" quotes directly into TimeW"' is a new tag.
Recorded TEST "tagging third task containing \"double\" quotes directly into TimeW"
  Started 2019-04-15T16:00:00
  Ended              17:00:00
  Total               1:00:00
```

TimeW still works at this point:

```
$ timew summ :id

Wk  Date       Day ID Tags                                                                       Start      End    Time   Total
W16 2019-04-15 Mon @3 TEST, tagging third task containing "double" quotes directly into TimeW 16:00:00 17:00:00 1:00:00
                   @2 TEST, first task                                                        18:50:02 18:51:19 0:01:17
                   @1 TEST, second task containing double quotes                              18:52:08        - 0:02:03 1:03:20

                                                                                                                        1:03:20
```

But only for the first time.  Reapeating the command gives me an error:

```
$ timew summ :id
Error: missing ':' at position 130
```

I straced it:

```
  550 1210481 [main] timew 20572 fhandler_base::open: 1 = fhandler_base::open(\??\C:\Users\saukrs\_\msys64\tmp\.timew\data\tags.data, 0x108000)
  702 1211183 [main] timew 20572 fhandler_base::open_fs: 1 = fhandler_disk_file::open(\??\C:\Users\saukrs\_\msys64\tmp\.timew\data\tags.data, 0x800
0)
  208 1211391 [main] timew 20572 open: 3 = open(/tmp/.timew/data/tags.data, 0x8000)
 1035 1212426 [main] timew 20572 _cygwin_istext_for_stdio: fd 3: opened as binary
 2313 1214739 [main] timew 20572 read: read(3, 0x60006AAF0, 1023) blocking
  874 1215613 [main] timew 20572 fhandler_base::read: returning 180, binary mode
 3985 1219598 [main] timew 20572 read: 180 = read(3, 0x60006AAF0, 180)
 3280 1222878 [main] timew 20572 read: read(3, 0x60006AAF0, 1023) blocking
 2035 1224913 [main] timew 20572 fhandler_base::read: returning 0, binary mode
  389 1225302 [main] timew 20572 read: 0 = read(3, 0x60006AAF0, 0)
 5599 1230901 [main] timew 20572 close: close(3)
  593 1231494 [main] timew 20572 fhandler_base::close: closing '/tmp/.timew/data/tags.data' handle 0x2E8
  272 1231766 [main] timew 20572 close: 0 = close(3)
Error: missing ':' at position 130--- Process 20572, exception 20474343 at 00007ffb93a1a388
--- Process 20572, exception 21474343 at 00007ffb93a1a388
--- Process 20572, exception 21474343 at 00007ffb93a1a388
--- Process 20572, exception 21474343 at 00007ffb93a1a388
--- Process 20572, exception 21474343 at 00007ffb93a1a388
89975 1321741 [main] timew 20572 write: 34 = write(2, 0x60006B328, 34)

 1026 1322767 [main] timew 20572 write: 1 = write(2, 0xFFFFC888, 1)
36395 1359162 [main] timew 20572 fhandler_base::fstat_helper: 0 = fstat (\??\C:\Users\saukrs\_\msys64\home\saukrs\debug\timewarrior_bugreport\strace_timew.txt, 0xFFFFC500) st_size=87191, st_mode=0100644, st_ino=34902897112134033st_atim=5CB4AE9B.37D24E5C st_ctim=5CB4AF1D.FBFBE2C st_mtim=5CB4AF1D.FBFBE2C st_birthtim=5CB4AE9B.37D24E5C
  404 1359566 [main] timew 20572 fstat64: 0 = fstat(1, 0xFFFFC500)
>> Timer timew 0.455686 sec

22306 1381872 [main] timew 20572 write: 29 = write(1, 0x60006B3E0, 29)
 2106 1383978 [main] timew 20572 do_exit: do_exit (65280), exit_state 1
  109 1384087 [main] timew 20572 void: 0x0 = signal (20, 0x1)
  147 1384234 [main] timew 20572 void: 0x0 = signal (1, 0x1)
  106 1384340 [main] timew 20572 void: 0x0 = signal (2, 0x1)
  105 1384445 [main] timew 20572 void: 0x0 = signal (3, 0x1)
```

Seems like it's checking the "tags.data" file:

```
$ ll /tmp/.timew/data/tags.data
-rw-r--r-- 1 saukrs Domain Users 180 Apr 15 18:54 /tmp/.timew/data/tags.data

$ cat /tmp/.timew/data/tags.data
{"TEST":{"count":3},"first task":{"count":1},"second task containing double quotes":{"count":1},"tagging third task containing \\"double\\" quotesdirectly into TimeW":{"count":1}}
```

I managed to continue to track my day job by installing v1.1.0 of the TimeW.   But it misses the `undo` command so I ask you for a fix.

**Comment by sskras** [comment] 2019-05-28 19:28
Any ideas on why does handling of double quotes differs between TaskWarrior and TimeWarrior?

**Comment by fdcds** [comment] 2019-07-10 17:57
Could the cause be the following?
```python
tag = '"double" quoted'
#> '"double" quoted'
str = '"{0}"'.format(tag)
#> '""double" quoted"'
shlex.split("timew {0}".format(str))
#> ['timew', 'double quoted']
```

**Comment by fdcds** [comment] 2019-07-10 18:07
#200 would also fix this.

**Comment by sruffell** [comment] 2019-11-13 12:23
I've added a trivial fix for the case of one set of embedded quotes, however, if JSON is going to be the disk format it *may* be worth using an external JSON parsing library that will handle the conversion when reading.  The library in libshared only removes the quotes around the outside, and not any embedded quotes, which is why I just stripped them here.

**Comment by lauft** [comment] 2019-11-20 21:07
The issue should be fixed with the commits mentioned above.

**Closed by lauft** 2019-11-20 21:07 UTC
Labels: bug
