### ISSUE TITLE
[Help wanted] passing a parameter to an extension

### ISSUE THREAD

**Issue by oivvio** [GothenburgBitFactory/timewarrior#476] opened 2022-01-20 14:17 UTC
I'd like to be able to pass a parameters to an extension without them  interfering with timewarrior's command parsing. 
I tried adding a double dash like so:

    timew my_extension  -- --extra args --goes here

But that doesn't work

**Comment by oivvio** [comment] 2022-02-02 07:24
Some further digging leads me to think that nothing like this is currently implemented. I'd like to promote this to a feature request. It would make extensions a lot more useful. Here's a simple use case:

    `timew pdfreport 1m -- --output /tmp/report.pdf`

**Comment by sruffell** [comment] 2022-02-02 13:33
I believe this is a duplicate of #230, and I agree it would be a useful feature.

**Comment by oivvio** [comment] 2022-02-02 19:08
@sruffell Thanks! The option of adding rc.key=value at the end of the invocation solves my problem. Maybe it should just be highlighted in the docs.

**Closed** 2022-02-09 09:42 UTC
