### ISSUE TITLE
At least one tag must be specified 

### ISSUE THREAD

**Issue by dennis-tra** [GothenburgBitFactory/timewarrior#306] opened 2020-04-21 09:20 UTC
Hi everyone,

thanks for your work - I just started using timewarrior.

Unfortunately I cannot tag a time slot with `daily`:
```
$ timew tag @2 'daily'                                                                                                                                                     
At least one tag must be specified. See 'timew help tag'.
```

For some reason if I omit the `d` it works with `aily`.

I suspect it's a problem with parsing the command line arguments?

**Comment by lauft** [comment] 2020-04-21 11:42
Timewarrior interprets `daily` as a datetime statement (see #60). The command line parsing is a bit to eager at this point. This is know and will be worked on in a future release.

**Comment by lauft** [comment] 2020-04-21 11:43
Duplicate of #60

**Closed by lauft** 2020-04-21 11:42 UTC

**Comment by dennis-tra** [comment] 2020-04-21 12:13
Great thanks for the fast reply
