### ISSUE TITLE
Modify tag name

### ISSUE THREAD

**Issue by wuxua** [GothenburgBitFactory/timewarrior#210] opened 2019-02-27 20:28 UTC
I want to change the name of a tag that I've used frequently. Instead of modifying hundreds of intervals with`tag` and `untag`, it would be nice if I could modify the name of the tag itself.

**Comment by nodens** [comment] 2020-03-04 19:59
Hi,
In case it helps someone, I currently have a function like this in my bash configuration:
```
# rename tag: use as timew-tagrename <oldtag> <newtag>
function timew-tagrename()
{
  oldtag=$1; shift
  newtag=$1; shift
  idlist=$(timew summary 1970W01 - now "$oldtag" :ids |\
    sed -nr 's/.* (@[0-9]+) .*/\1/p')

  timew tag $idlist "$newtag"
  timew untag $idlist "$oldtag"
} 
```

Note that this doesn't take care of the tag description for instance. Renaming tag would be better :)

**Comment by lauft** [comment] 2020-03-06 18:09
Duplicate of #179

**Closed** 2020-03-06 18:09 UTC
Labels: duplicate, enhancement

**Comment by adrianschlatter** [comment] 2023-06-20 07:59
Thanks a lot @nodens for your tagrename function. For those that use zsh, here's a translation

```
function timew-tagrename()
{
        local oldtag=$1; shift
        local newtag=$1; shift
        local idlist=$(timew summary 1970W01 - now "$oldtag" :ids |\
                       sed -nr 's/.* (@[0-9]+) .*/\1/p')
        echo "$idlist" | xargs -I ids timew tag ids "$newtag"
        echo "$idlist" | xargs -I ids timew untag ids "$oldtag"
}
```

> Hi, In case it helps someone, I currently have a function like this in my bash configuration:
> 
> ```
> # rename tag: use as timew-tagrename <oldtag> <newtag>
> function timew-tagrename()
> {
>   oldtag=$1; shift
>   newtag=$1; shift
>   idlist=$(timew summary 1970W01 - now "$oldtag" :ids |\
>     sed -nr 's/.* (@[0-9]+) .*/\1/p')
> 
>   timew tag $idlist "$newtag"
>   timew untag $idlist "$oldtag"
> } 
> ```
> 
> Note that this doesn't take care of the tag description for instance. Renaming tag would be better :)
