### ISSUE TITLE
v1.2.0-5ab9b86 (Feb 23 2020) gives wrong :id when filtering 

### ISSUE THREAD

**Issue by sskras** [GothenburgBitFactory/timewarrior#293] opened 2020-02-29 21:20 UTC
I updated to dev and removed my 2 bytes long `tags.data` file. And the first run it got successfully recreated:
```
$ rm ~/.timewarrior/data/tags.data
$ timew summ
Tags database does not exist. Recreating from interval data...

Wk Date       Day Tags                                                                                                        Start      End    Time   Total
W9 2020-02-29 Sat [organze], fix broken TimeWarrior v1.2.0, accidentally tags.data file (JSON) got truncated to zero bytes 20:16:10 20:59:07 0:42:57
                  [.nonwo.], text / browse                                                                                 20:59:07 21:31:25 0:32:18
                  [organze], fix broken TimeWarrior v1.2.0, accidentally tags.data file (JSON) got truncated to zero bytes 21:31:25 22:14:45 0:43:20
                  [.rest......], wc.                                                                                       22:14:46 22:17:15 0:02:29
                  [.rest......], eat / drink                                                                               22:17:16 22:42:12 0:24:56
                  [organze], go reg working time                                                                           22:42:12        - 0:28:06 2:54:06

                                                                                                                                                     2:54:06

$ ll ~/.timewarrior/data/tags.data
-rw-r--r-- 1 saukrs Domain Users 75K Feb 29 23:10 /home/saukrs/.timewarrior/data/tags.data
```

Now if I search for some tag via grep, it gives me right IDs -- `@826` and `@444`:
```
$ timew summ :id :year | grep -- '--- monthly time declaration mark ---'
W1 2020-01-03 Fri @826 --- monthly time declaration mark ---, [pro-time]                                                                                                          10:00:07 10:00:08 0:00:01
                  @444 --- monthly time declaration mark ---, [pro-time]                                                                                                          23:46:52 23:46:56 0:00:04
```

But if I search for it directly via TimeW, ID of the second one, `@825` is falsely shown as equal to the decremented first one, `@826`:
```
$ timew summ :id :year '--- monthly time declaration mark ---'

Wk Date       Day ID   Tags                                                 Start      End    Time   Total
W1 2020-01-03 Fri @826 --- monthly time declaration mark ---, [pro-time] 10:00:07 10:00:08 0:00:01 0:00:01
W5 2020-01-31 Fri @825 --- monthly time declaration mark ---, [pro-time] 23:46:52 23:46:56 0:00:04 0:00:04

                                                                                                   0:00:05
```

Do you know a commit which avoids this bug so I could quickly rollback please?
Ping @sruffell 

---
```
$ timew diag

timew 1.2.0
       Platform: <unknown>

Compiler:
        Version: 7.3.0
           Caps: +stdc +stdc_hosted +200809 +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Feb 29 2020 20:46:30
         Commit: 5ab9b86
          CMake: 3.13.2
     Build type: release

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/saukrs/.timewarrior/timewarrior.cfg (-rw- 64 bytes)
       Database: /home/saukrs/.timewarrior (drwx 0 bytes)
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/saukrs/.timewarrior/extensions (drwx 0 bytes)
               (None)
```

**Comment by sruffell** [comment] 2020-02-29 21:26
>Do you know a commit which avoids this bug so I could quickly rollback please?

Well, bummer. If I had to guess, it *sounds* like it would be the change that does not load the entire database which I added.  You could try tag `v1.2.0` to see if it is fixed there.

However, do you think you could give me a set of instructions from a brand new database that will reproduce so I can look into it?

**Comment by sruffell** [comment] 2020-02-29 21:41
Specifically, the problem is that I did not account for non-contiguous ranges of intervals as seen here: https://github.com/GothenburgBitFactory/timewarrior/blob/dev/src/data.cpp#L741-L745

**Comment by sskras** [comment] 2020-02-29 21:42
Thanks. No need to hurry then.

Local time here is running out for me to declare my two months of my enterprise activity. And my accounting script is broken now.  After 20 minutes it will be March.

So I will skip the accounting and will try to fake my time declaration : (

**Comment by sruffell** [comment] 2020-02-29 21:44
I still think 1.2.0 will work for you if you wanted to build and try that.

**Comment by sskras** [comment] 2020-02-29 22:00
You're right, I built **v1.2.0**, 1d27150 dated Nov 22 2019:
```
$ timew diag
Tag info database does not exist. Recreating from interval data...

timew 1.2.0
       Platform: <unknown>

Compiler:
        Version: 7.3.0
           Caps: +stdc +stdc_hosted +200809 +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Feb 29 2020 23:49:38
         Commit: 1d27150
          CMake: 3.13.2
     Build type: debug
```
... and now it works:
```
$ timew summ :id :year '--- monthly time declaration mark ---'

Wk Date       Day ID   Tags                                                 Start      End    Time   Total
W1 2020-01-03 Fri @826 --- monthly time declaration mark ---, [pro-time] 10:00:07 10:00:08 0:00:01 0:00:01
W5 2020-01-31 Fri @444 --- monthly time declaration mark ---, [pro-time] 23:46:52 23:46:56 0:00:04 0:00:04

                                                                                                   0:00:05
```

I got 1 minutes minutes til the midnight : D
Thank you for the quick responses nevertheless : )

**Comment by sruffell** [comment] 2020-02-29 22:57
@sskras sorry about that again. I've submitted a pull request with the fix for this, so hopefully you'll be willing to run from the dev branch again.

**Closed** 2020-03-06 15:10 UTC
