### ISSUE TITLE
Time calculated way over actual time

### ISSUE THREAD

**Issue by GurvanKervern** [GothenburgBitFactory/timewarrior#447] opened 2021-08-30 15:56 UTC
It is a problem I have noticed a number of time but I'm not sure what circumstances lead to it : 
```
~$ timew
Tracking XXX YYY
  Started 2021-08-30T15:41:08
  Current            23:50:55
  Total              15:43:44

```
In summary or week the time is shown correctly, but here as you can see it reports too much time. earlier today it reported about 4-5 hours too much but now it's nearly the double, more than 7 hours.

I'm using timewarrior 1.2.0 on Ubuntu 20.04

**Comment by sruffell** [comment] 2021-08-30 16:22
I believe this may be a duplicate of #248, which is resolved in version 1.4.0.

Is the time your seeing the summation of all recent consecutive intervals with the same tag?

**Comment by lauft** [comment] 2021-08-30 16:25
As suggested in #446 (and by @sruffell), the first measure would be to upgrade to the most recent version of Timewarrior. But unless you want to build it yourself, you are stuck with the version provided by Ubuntu 20.04... 🤔

Those packages are not provided by us, so we need to contact the respective maintainers and ask them to upgrade.

**Comment by GurvanKervern** [comment] 2021-08-30 16:41
> I believe this may be a duplicate of #248, which is resolved in version 1.4.0.
> 
> Is the time your seeing the summation of all recent consecutive intervals with the same tag?

Thank you, it seems you're right : 
`
W34 2021-08-28 Sat XXX, YYY, pomodoro 17:50:54 20:52:51 3:01:57  3:01:57
W34 2021-08-29 Sun XXX, YYY           16:32:46  0:00:00 7:27:14  7:27:14
W35 2021-08-30 Mon XXX, YYY            0:00:00  0:06:43 0:06:43
                   XXX, YYY           15:41:08        - 8:18:52  8:25:35
W35 2021-08-31 Tue XXX, YYY            0:00:00        - 0:39:17  0:39:17
`
All similar activities since Sunday (before the "pomodoro" tag) are grouped together

**Comment by GurvanKervern** [comment] 2021-08-30 16:46
> As suggested in #446 (and by @sruffell), the first measure would be to upgrade to the most recent version of Timewarrior. But unless you want to build it yourself, you are stuck with the version provided by Ubuntu 20.04... thinking
> 
> Those packages are not provided by us, so we need to contact the respective maintainers and ask them to upgrade.

Well I would rather use my distro's package so it is upgraded automatically all the time (hopefully :p), without me having to cd to 50 folders to git pull every tool I use daily :)

**Comment by lauft** [comment] 2021-08-30 19:11
@GurvanKervern you could install the following PPA to get the recent version of Timewarrior: https://launchpad.net/~chronitis/+archive/ubuntu/misc

**Comment by GurvanKervern** [comment] 2021-08-30 19:23
@lauft Ok, thank you :)

**Closed** 2021-08-31 07:29 UTC
Labels: discussion, solved
