### ISSUE TITLE
Tests with synthetic interval fail when test intervals cross day border

### ISSUE THREAD

**Issue by sruffell** [GothenburgBitFactory/timewarrior#260] opened 2019-11-13 10:09 UTC
I'm not sure what this problem is, or whether it is just in the test or not, but I thought I would take this note just in case.

I was noticing that all the tests with synthetic intervals were failing this morning and then stopped failing. I then set the time on my system back a half-hour and the test was failing again.

Note that in the output below I've added some extra prints to display the time values and results of the export because I was trying to figure out why the assertion was failing. 

```
$ test/annotate.t
1..9
ok 1 - annotate.t: Add an annotation to a closed interval
ok 2 - annotate.t: Add an annotation to multiple intervals
ok 3 - annotate.t: Add an annotation to an open interval
ok 4 - annotate.t: Annotate a synthetic interval.
# exclusions  2019-11-13 06:02:06.311965 , 2019-11-13 07:02:06.311965
# Now utc:  2019-11-13 10:02:06.311965
# Now       2019-11-13 04:02:06.311946
# {u'start': u'20191113T050206Z', u'end': u'20191113T060206Z', u'annotation': u'bar', u'tags': [u'foo']}
# {u'start': u'20191113T070206Z', u'tags': [u'foo']}
ok 5 - annotate.t: Call 'annotate' with identical ids
ok 6 - annotate.t: Calling 'annotate' without annotation removes annotation
ok 7 - annotate.t: Adding annotation with missing id on empty database is an error
ok 8 - annotate.t: Adding annotation with missing id on inactive time tracking is an error
ok 9 - annotate.t: Use open interval when adding annotation with missing id and active time tracking
$ date
Wed Nov 13 04:02:09 CST 2019
$ date
Wed Nov 13 03:31:03 CST 2019
$ test/annotate.t
1..9
ok 1 - annotate.t: Add an annotation to a closed interval
ok 2 - annotate.t: Add an annotation to multiple intervals
ok 3 - annotate.t: Add an annotation to an open interval
not ok 4 - annotate.t: Annotate a synthetic interval.
# FAIL: AssertionError on file test/annotate.t line 163 in test_annotate_synthetic_interval: 'self.assertEqual(len(j), 2)':
#       3 != 2
# exclusions  2019-11-13 05:31:05.682532 , 2019-11-13 06:31:05.682532
# Now utc:  2019-11-13 09:31:05.682532
# Now       2019-11-13 03:31:05.682493
# {u'start': u'20191113T043105Z', u'end': u'20191113T053105Z', u'annotation': u'bar', u'tags': [u'foo']}
# {u'start': u'20191113T063105Z', u'end': u'20191114T053105Z', u'tags': [u'foo']}
# {u'start': u'20191114T060000Z', u'tags': [u'foo']}
ok 5 - annotate.t: Call 'annotate' with identical ids
ok 6 - annotate.t: Calling 'annotate' without annotation removes annotation
ok 7 - annotate.t: Adding annotation with missing id on empty database is an error
ok 8 - annotate.t: Adding annotation with missing id on inactive time tracking is an error
ok 9 - annotate.t: Use open interval when adding annotation with missing id and active time tracking
```

**Comment by sruffell** [comment] 2019-11-13 10:53
I added a rule to skip these particular tests if the interval crosses dates for the time being until a proper fix to the test can be implemented.

**Comment by lauft** [comment] 2019-11-15 22:07
I cannot reproduce this on my machine (Darwin). Using [faketime](https://github.com/wolfcw/libfaketime) to run the test at different times (via the `timemachine` helper script in `test`) I found  no error. However I am using `CET` not `CST` like you. Could that be an explanation?

**Comment by sruffell** [comment] 2019-11-17 17:32
You're right (and thanks for pointing out that faketime can be used here). The timezone definitely has an impact. If I run the following shell snippet I get 4 failures, but at different times than I get for my local timezone:


```shell
for x in {0..23}; do
  TEST_TIME="2019-11-17T${x}:01:00 CET";
  echo "${TEST_TIME}";
  faketime "${TEST_TIME}" test/annotate.t TestAnnotate.test_annotate_synthetic_interval;
done
```

Fails for me on Ubuntu 18.04.3 like:
```
...
2019-11-17T7:01:00 CET
1..1
not ok 1 - annotate.t: Annotate a synthetic interval.
# FAIL: AssertionError on file test/annotate.t line 157 in test_annotate_synthetic_interval: 'self.assertEqual(len(j), 2)':
#       3 != 2
2019-11-17T8:01:00 CET
1..1
not ok 1 - annotate.t: Annotate a synthetic interval.
# FAIL: AssertionError on file test/annotate.t line 157 in test_annotate_synthetic_interval: 'self.assertEqual(len(j), 2)':
#       3 != 2
2019-11-17T9:01:00 CET
1..1
not ok 1 - annotate.t: Annotate a synthetic interval.
# FAIL: AssertionError on file test/annotate.t line 157 in test_annotate_synthetic_interval: 'self.assertEqual(len(j), 2)':
#       3 != 2
2019-11-17T10:01:00 CET
1..1
not ok 1 - annotate.t: Annotate a synthetic interval.
# FAIL: AssertionError on file test/annotate.t line 157 in test_annotate_synthetic_interval: 'self.assertEqual(len(j), 2)':
#       3 != 2
...
```

Also, my check to skip is not sufficient, since if I run it, I still get 3 failures and one skip:
```

**Comment by lauft** [comment] 2019-11-17 20:21
Another point to consider: Is this a problem of timewarrior, or of the asserts in the python tests/library?

**Comment by sruffell** [comment] 2019-11-18 05:36
This does appear to be a problem in timewarrior itself, although it is not yet clear the best way to solve it.

From the tip of the current dev branch, I would imagine you could reproduce the problem like:
```
$ TZ="GMT" faketime "2019-11-17T1:00:00 GMT" test/annotate.t TestAnnotate.test_annotate_synthetic_interval
1..1
not ok 1 - annotate.t: Annotate a synthetic interval.
# FAIL: AssertionError on file test/annotate.t line 157 in test_annotate_synthetic_interval: 'self.assertEqual(len(j), 2)':
#       3 != 2
```

To eliminate python you could run the following script:
```bash
#/bin/sh

rm -fr timewarrior.cfg
rm -fr data
export TIMEWARRIORDB=$(pwd)
export TZ="GMT"

src/timew config exclusions.saturday 21:00:00-22:00:00 :yes
src/timew config exclusions.sunday 21:00:00-22:00:00 :yes

faketime "2019-11-17T00:00:00" src/timew start "2019-11-16T20:00:00"
cat $TIMEWARRIORDB/data/2019-11.data
faketime "2019-11-17T00:00:00" src/timew tag @2 "test"
cat $TIMEWARRIORDB/data/2019-11.data
```

Which on my system produces the following output:
```shell
$ ./test.sh
Config file /home/sruffell/projects/timewarrior/timewarrior.cfg modified.
Config file /home/sruffell/projects/timewarrior/timewarrior.cfg modified.
Tracking
  Started 2019-11-16T20:00:00
  Current         17T00:00:00
  Total               4:00:00
inc 20191116T200000Z
Note: 'test' is a new tag.
Added test to @2
inc 20191116T200000Z - 20191116T210000Z # test
inc 20191116T220000Z - 20191117T210000Z
inc 20191117T220000Z
```

You can see when after the tag is added, the single open interval is "flattened" to create 2 closed intervals and one open interval, which is wrong.

If the flatten function is modified such that it does not use an open interval when looking for enclosed exclusions like below, the test.sh script from above will work.

```diff
diff --git a/src/data.cpp b/src/data.cpp
index 9677000..0e30b0d 100644
--- a/src/data.cpp
+++ b/src/data.cpp
@@ -368,16 +368,20 @@ std::vector <Interval> subset (
 ////////////////////////////////////////////////////////////////////////////////
 std::vector <Interval> flatten (
   const Interval& interval,
   const std::vector <Range>& exclusions)
 {
   std::vector <Interval> all;
+  Interval closed {interval};
+
+  if (closed.is_open ())
+    closed.close();

   std::vector <Range> enclosed;
   for (auto& e : exclusions)
-    if (interval.encloses (e))
+    if (closed.encloses (e))
       enclosed.push_back (e);

   Datetime now;
   for (auto& result : subtractRanges ({interval}, enclosed))
   {
     Interval chunk {interval};
```

And here is the output from test.sh which looks as I would expect:

```shell
$ ./test.sh
Config file /home/sruffell/projects/timewarrior/timewarrior.cfg modified.
Config file /home/sruffell/projects/timewarrior/timewarrior.cfg modified.
Tracking
  Started 2019-11-16T20:00:00
  Current         17T00:00:00
  Total               4:00:00
inc 20191116T200000Z
Note: 'test' is a new tag.
Added test to @2
inc 20191116T200000Z - 20191116T210000Z # test
inc 20191116T220000Z
```

But I would *expect* that the exclusions passed to flatten are wrong, and should not include any that do not overlap with the start of an open interval and the current time.  But I do not yet understand this part of the code well enough to say that for sure.

**Comment by lauft** [comment] 2019-11-19 21:49
Exclusions are only applied to an open interval. When applied they generate so called synthetic intervals which only exist virtually as long as the open interval exists.

If the open interval is closed, the exclusions are applied and thus the synthetic intervals are persisted in the database. 
If a synthetic interval is modified (deleted, tagged, ...) all synthetic intervals up to this interval are persisted (and thus moving the start of the open interval forward).

In your example the open interval starts at 20:00, spanning the exclusion from 21:00 to 22:00, thus creating two virtual intervals (closed 20:00 - 21:00 and open 22:00 - "now").

Tagging interval `@2` should then result in persisting the closed interval and creating a new open interval starting at 22:00. 

So our expectations match. :)

Doing some testing I think the reason for the bug is the defined exclusion ahead of the current datetime. In `src/Exclusion.cpp:128` I found that if the given interval is open, closes it at `Datetime('tomorrow')` which is obviously too much. Setting this to `Datetime()` (= current datetime) also seems to fix the problem.

**Comment by sruffell** [comment] 2019-11-19 22:33
I'll second your analysis.  The below change eliminates the exclusions that start in the future to flatten, which, when I was looking at it on Sunday, seemed to me like the root problem.

```diff
diff --git a/src/Exclusion.cpp b/src/Exclusion.cpp
index 0784451..ad6dd44 100644
--- a/src/Exclusion.cpp
+++ b/src/Exclusion.cpp
@@ -125,7 +125,7 @@ std::vector <Range> Exclusion::ranges (const Range& range) const

     if (myRange.is_open())
     {
-      myRange.end = Datetime("tomorrow");
+      myRange.end = Datetime();
     }

     while (start <= myRange.end)
```

**Comment by lauft** [comment] 2019-11-20 05:52
While I am already at it, I will push this small fix directly to the repository. Big thanks to you for your contribution to solving this issue nontheless!

**Closed** 2019-11-20 05:58 UTC
Labels: bug
